In [2]:
import numpy as np
import pandas as pd
import sklearn as sk
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline     

df = pd.read_csv("pokerhand.csv")
df.head(5) #checking out the data

   suit1  rank1  suit2  rank2  suit3  rank3  suit4  rank4  suit5  rank5  hand
0      1      1      1     13      2      4      2      3      1     12     0
1      3     12      3      2      3     11      4      5      2      5     1
2      1      9      4      6      1      4      3      2      3      9     1
3      1      4      3     13      2     13      2      1      3      6     1
4      3     10      2      7      1      2      2     11      4      9     0

In [34]:
#making the data readable
def suits(value):
    if(value==1):
        return "Hearts"
    if(value==2):
        return "Spades"
    if(value==3):
        return "Diamonds"
    if(value==4):
        return "Clubs"

def FaceCards(value):
    if(value==1):
        return "Ace"
    if(value==11):
        return "Jack"
    if(value==12):
        return "Queen"
    if(value==13):
        return "King"
    return value

def Hand(value):
    if(value==0):
        return "nothing"
    if(value==1):
        return "Pair"
    if(value==2):
        return "two Pairs"
    if(value==3):
        return "Three of a kind"
    if(value==4):
        return "Straight"    
    if(value==5):
        return "Flush"
    if(value==6):
        return "Full house"
    if(value==7):
        return "Four of a kind"
    if(value==8):
        return "Straight flush"
    if(value==9):
        return "Royal straight flush"

#for i in df.index:
#    df.loc[i,"suit1"] = suits(df.loc[i,"suit1"])
#    df.loc[i,"rank1"] = FaceCards(df.loc[i,"rank1"])
#    df.loc[i,"suit2"] = suits(df.loc[i,"suit2"])
#    df.loc[i,"rank2"] = FaceCards(df.loc[i,"rank2"])
#    df.loc[i,"suit3"] = suits(df.loc[i,"suit3"])
#    df.loc[i,"rank3"] = FaceCards(df.loc[i,"rank3"])
#    df.loc[i,"suit4"] = suits(df.loc[i,"suit4"])
#    df.loc[i,"rank4"] = FaceCards(df.loc[i,"rank4"])
#    df.loc[i,"suit5"] = suits(df.loc[i,"suit5"])
#    df.loc[i,"rank5"] = FaceCards(df.loc[i,"rank5"])


#df.to_csv("pokerhandReadable.csv");
#df.head(5)
len(df.index)

1000000

In [31]:
allSuits = np.concatenate((df["suit1"].tolist() , df["suit2"].tolist() ,df["suit3"].tolist(), df["suit4"].tolist() ,df["suit5"].tolist()), axis=0);
print(len(allSuits))
allCards =np.concatenate((df["rank1"].tolist() , df["rank2"].tolist() ,df["rank3"].tolist(), df["rank4"].tolist() ,df["rank5"].tolist()), axis=0);
print(len(allCards))

cardCounts = { "Hearts Ace": 0, "Hearts 2": 0,"Hearts 3": 0, "Hearts 4": 0,"Hearts 5": 0, "Hearts 6": 0,"Hearts 7": 0, "Hearts 8": 0,"Hearts 9": 0, "Hearts 10": 0, "Hearts Jack": 0, "Hearts Queen": 0,"Hearts King": 0, "Spades Ace": 0, "Spades 2": 0,"Spades 3": 0, "Spades 4": 0,"Spades 5": 0, "Spades 6": 0,"Spades 7": 0, "Spades 8": 0,"Spades 9": 0, "Spades 10": 0,"Spades Jack": 0, "Spades Queen": 0,"Spades King": 0,"Diamonds Ace": 0, "Diamonds 2": 0,"Diamonds 3": 0, "Diamonds 4": 0,"Diamonds 5": 0, "Diamonds 6": 0,"Diamonds 7": 0, "Diamonds 8": 0,"Diamonds 9": 0, "Diamonds 10": 0, "Diamonds Jack": 0, "Diamonds Queen": 0,"Diamonds King": 0,"Clubs Ace": 0, "Clubs 2": 0,"Clubs 3": 0, "Clubs 4": 0,"Clubs 5": 0, "Clubs 6": 0,"Clubs 7": 0, "Clubs 8": 0,"Clubs 9": 0, "Clubs 10": 0, "Clubs Jack": 0, "Clubs Queen": 0,"Clubs King": 0};
count = 0
for i in np.nditer(allSuits):
    suit = suits(i);
    card = FaceCards(allCards[count]);
    cardCounts[suit + " " + str(card)] = cardCounts[suit + " " + str(card)] +1;
    count = count +1;
    
for key in cardCounts:
    print(key + " has " + str(cardCounts[key]) + " cards")

5000000
5000000
Clubs Jack has 96090 cards
Hearts King has 96036 cards
Diamonds Queen has 96175 cards
Clubs 5 has 96109 cards
Hearts 10 has 96116 cards
Spades King has 95574 cards
Clubs 2 has 96613 cards
Hearts Jack has 96202 cards
Hearts 3 has 96423 cards
Hearts Queen has 96008 cards
Hearts 8 has 96398 cards
Spades 3 has 95905 cards
Hearts 7 has 96418 cards
Spades Ace has 96270 cards
Hearts 5 has 95932 cards
Hearts 6 has 96485 cards
Clubs 7 has 96347 cards
Diamonds 9 has 96177 cards
Spades 2 has 95464 cards
Spades Queen has 96221 cards
Spades 7 has 96344 cards
Spades 9 has 95902 cards
Diamonds 4 has 96357 cards
Clubs Queen has 96135 cards
Diamonds 7 has 96378 cards
Clubs 4 has 96411 cards
Spades 8 has 95969 cards
Clubs King has 96211 cards
Clubs 10 has 95625 cards
Hearts Ace has 96260 cards
Diamonds 10 has 96646 cards
Spades 4 has 96068 cards
Spades Jack has 96106 cards
Clubs 8 has 96083 cards
Diamonds King has 96698 cards
Spades 6 has 95914 cards
Clubs 3 has 96236 cards
Hearts 9 has 96076 cards
Clubs 9 has 95618 cards
Diamonds 3 has 96221 cards
Spades 5 has 95846 cards
Diamonds Jack has 96431 cards
Clubs Ace has 96213 cards
Hearts 4 has 95834 cards
Hearts 2 has 96448 cards
Diamonds 8 has 96160 cards
Clubs 6 has 96325 cards
Diamonds Ace has 95907 cards
Diamonds 5 has 96042 cards
Diamonds 2 has 96793 cards
Spades 10 has 96059 cards
Diamonds 6 has 95721 cards

In [40]:
#0: Nothing in hand; not a recognized poker hand 
#1: One pair; one pair of equal ranks within five cards 
#2: Two pairs; two pairs of equal ranks within five cards 
#3: Three of a kind; three equal ranks within five cards 
#4: Straight; five cards, sequentially ranked with no gaps 
#5: Flush; five cards with the same suit 
#6: Full house; pair + different rank three of a kind 
#7: Four of a kind; four equal ranks within five cards 
#8: Straight flush; straight + flush 
#9: Royal flush; {Ace, King, Queen, Jack, Ten} + flush 
    
sets = {"nothing": 0, "Pair":0,"two Pairs":0,"Three of a kind":0,"Straight":0,"Flush":0,"Full house":0,"Four of a kind":0,"Straight flush":0,"Royal straight flush":0}
listOfHands = df["hand"].tolist();

for x in listOfHands:
    sets[Hand(x)] = sets[Hand(x)] +1;
    
for key in sets:
    print(key + " has occured " + str(sets[key]) + " times")

Four of a kind has occured 230 times
Three of a kind has occured 21121 times
Full house has occured 1424 times
Royal straight flush has occured 3 times
Pair has occured 422498 times
Straight has occured 3885 times
Straight flush has occured 12 times
nothing has occured 501209 times
Flush has occured 1996 times
two Pairs has occured 47622 times